param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\works\program\IAR8.3\common\bin\cspybat" -f "H:\迅雷下载\共享资料\【a新整理资料】\【平衡小车之家】电磁巡线传感器附送资料\3.K60电磁巡线例程\Project\settings\K60_2WD.Debug.general.xcl" --backend -f "H:\迅雷下载\共享资料\【a新整理资料】\【平衡小车之家】电磁巡线传感器附送资料\3.K60电磁巡线例程\Project\settings\K60_2WD.Debug.driver.xcl" 
}
else
{
& "D:\works\program\IAR8.3\common\bin\cspybat" -f "H:\迅雷下载\共享资料\【a新整理资料】\【平衡小车之家】电磁巡线传感器附送资料\3.K60电磁巡线例程\Project\settings\K60_2WD.Debug.general.xcl" --debug_file=$debugfile --backend -f "H:\迅雷下载\共享资料\【a新整理资料】\【平衡小车之家】电磁巡线传感器附送资料\3.K60电磁巡线例程\Project\settings\K60_2WD.Debug.driver.xcl" 
}
