del Release\obj\*.*     /q
del Release\obj\*.pbi     /q
del Release\obj\*.xcl    /q
del Release\obj\*.pbd    /q
del Release\obj\*.browse    /q
del Release\obj\*.linf      /q
del Release\Exe\*.out    /q
del Release\Exe\*.sim    /q
del Release\Exe\*.*    /q

del Debug\obj\*.o     /q
del Debug\obj\*.pbi     /q
del Debug\obj\*.xcl    /q
del Debug\obj\*.pbd    /q
del Debug\obj\*.browse    /q
del Debug\obj\*.linf      /q
del Debug\Exe\*.out    /q
del Debug\Exe\*.sim    /q
del Debug\Exe\*.*    /q